# Generated by Django 5.2.1 on 2025-06-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0002_alter_student_evaluation_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('TEACHER', 'Teacher'), ('ASSISTANT', 'Assistant'), ('ADMIN', 'Administrator'), ('Nurse', 'Medical')], max_length=20),
        ),
    ]
