# Generated by Django 5.2.1 on 2025-06-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0003_alter_staff_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdocument',
            name='doc_type',
            field=models.CharField(choices=[('BIRTH_CERT', 'Birth Certificate'), ('MEDICAL', 'Medical Record'), ('ID', 'ID'), ('passport', 'passport')], max_length=20),
        ),
    ]
